-- MySQL Script generated by MySQL Workbench
-- Fri Jun 14 16:05:36 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Guia1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Guia1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Guia1` DEFAULT CHARACTER SET utf8 ;
USE `Guia1` ;

-- -----------------------------------------------------
-- Table `Guia1`.`privilegios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guia1`.`privilegios` (
  `idPerfil` INT NOT NULL AUTO_INCREMENT,
  `nombrePrivilegio` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idPerfil`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Guia1`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guia1`.`usuarios` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `idPrivilegio` INT NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `usuario` VARCHAR(50) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `fecha_registro` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `priviUser_idx` (`idPrivilegio` ASC),
  CONSTRAINT `priviUser`
    FOREIGN KEY (`idPrivilegio`)
    REFERENCES `Guia1`.`privilegios` (`idPerfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Guia1`.`publicaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guia1`.`publicaciones` (
  `idpublicacion` INT NOT NULL AUTO_INCREMENT,
  `idUserPublico` INT NOT NULL,
  `contenidoPublicacion` LONGTEXT NOT NULL,
  `fechaPublicacion` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idpublicacion`),
  INDEX `publicacioesUser_idx` (`idUserPublico` ASC),
  CONSTRAINT `publicacioesUser`
    FOREIGN KEY (`idUserPublico`)
    REFERENCES `Guia1`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `Guia1`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guia1`.`likes` (
  `idlike` INT NOT NULL AUTO_INCREMENT,
  `idPublicacion` INT NOT NULL,
  PRIMARY KEY (`idlike`),
  INDEX `publiLikes_idx` (`idPublicacion` ASC),
  CONSTRAINT `publiLikes`
    FOREIGN KEY (`idPublicacion`)
    REFERENCES `Guia1`.`publicaciones` (`idpublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Guia1`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guia1`.`comentarios` (
  `idcomentario` INT NOT NULL AUTO_INCREMENT,
  `idPublicacion` INT NOT NULL,
  `contenidoComentario` LONGTEXT NOT NULL,
  `fechaComentario` TIMESTAMP NOT NULL,
  PRIMARY KEY (`idcomentario`),
  INDEX `comentarioPublicacion_idx` (`idPublicacion` ASC),
  CONSTRAINT `comentarioPublicacion`
    FOREIGN KEY (`idPublicacion`)
    REFERENCES `Guia1`.`publicaciones` (`idpublicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Guia1`.`fotos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guia1`.`fotos` (
  `idFoto` INT NOT NULL AUTO_INCREMENT,
  `nombreFoto` VARCHAR(200) NOT NULL,
  `rutaFoto` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idFoto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Guia1`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Guia1`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `idUsuario` INT NOT NULL,
  `idFoto` INT NOT NULL,
  `nombreCompleto` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idperfil`),
  INDEX `perfilUser_idx` (`idUsuario` ASC),
  INDEX `fotoUsuario_idx` (`idFoto` ASC),
  CONSTRAINT `perfilUser`
    FOREIGN KEY (`idUsuario`)
    REFERENCES `Guia1`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fotoUsuario`
    FOREIGN KEY (`idFoto`)
    REFERENCES `Guia1`.`fotos` (`idFoto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;